load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "hello",
    url = "http://ftp.gnu.org/gnu/hello/hello-1.3.tar.gz",
    build_file = "//:hello.bazel",
    strip_prefix = "hello-1.3",
)

local_repository(
    name = "greeting",
    path = "../greeting",
)
